#spring 数据库配置 
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/xone?useSSL=false&allowPublicKeyRetrieval=true
    username: root
#linux
    password: Yao;9605001
#windows
#    password: 9605001
    driver-class-name: com.mysql.jdbc.Driver
#create update
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

#thymelea模板配置 这是不必要填的 填在配置文件里面默认覆盖
#  thymeleaf:
#    cache: false
#    mode: LEGACYHTML5
#    prefix: classpath:/templates/
#    suffix: .html
#    encoding: UTF-8
#    servlet:
#      content-type: text/html

  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
# spring.redis.database=0
# Redis服务器地址
#spring.redis.host=localhost
# Redis服务器连接端口
#spring.redis.port=6379
# Redis服务器连接密码（默认为空）
#spring.redis.password=
# 连接池最大连接数（使用负值表示没有限制）
#spring.redis.pool.max-active=8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.pool.max-wait=-1
# 连接池中的最大空闲连接
#spring.redis.pool.max-idle=8
# 连接池中的最小空闲连接
#spring.redis.pool.min-idle=0
# 连接超时时间（毫秒）
#spring.redis.timeout=0

#uid生成器策略参数
#	/**
#	 * 关于UID比特分配的建议 对于并发数要求不高、期望长期使用的应用, 可增加timeBits位数, 减少seqBits位数.
#	 * 例如节点采取用完即弃的WorkerIdAssigner策略, 重启频率为12次/天,
#	 * 那么配置成{"workerBits":23,"timeBits":31,"seqBits":9}时, 可支持28个节点以整体并发量14400
#	 * UID/s的速度持续运行68年.
#	 *  
#	 * 对于节点重启频率频繁、期望长期使用的应用, 可增加workerBits和timeBits位数, 减少seqBits位数.
#	 * 例如节点采取用完即弃的WorkerIdAssigner策略, 重启频率为24*12次/天,
#	 * 那么配置成{"workerBits":27,"timeBits":30,"seqBits":6}时, 可支持37个节点以整体并发量2400
#	 * UID/s的速度持续运行34年.
#	 */
#     
com: 
  gosun:
    uid:
      time-bits: 31
      worker-bits: 23
      seq-bits: 9
      generator: xoneIdentityGenerator

#允许跨域访问的url定义 ，多个URL之间以,号分隔
service: 
  cros:
    registry:
    #注意：此处的MAPING在后台会删除字串中的前后空格
      mapping: "/api/**,/sec/**"
      origins: "*"  #定义来源域名
      headers: "*"  
      methods: "*"
      credentials: true
      maxage: 3600
      exposed:
        headers: Authorization